craigjmidwinter/total-connect-client

README.md, total_connect_client/TotalConnectClient.py
Confirmed on my Total Connect system.
=> Add additional arming states (instant, night, etc.)

.gitignore, total_connect_client/TotalConnectClient.py
This PR resolves issue #2 by adding the ability to get the status of all zones in a given location.
=> Issue #2: Adding the ability to retrieve zone statuses

total_connect_client/TotalConnectClient.py, total_connect_client/test.py
Changed from Exception to logging.info when seeing an unknown device.
Otherwise it halts when running inside homeassistant.
Reduced output of test.py so it's more readable.
Sorry...it worked fine outside of homeassistant, but when inside I saw the errors.
=> Added self. before VALID_DEVICES.

total_connect_client/TotalConnectClient.py
=> Added GSMVLP5-4G to devicelist

setup.py
pypi is at version `0.23` but `setup.py` still has `0.21`.  This PR updates `setup.py` to reflect the latest version on pypi
=> update setup with latest version on pypi

total_connect_client/TotalConnectClient.py, total_connect_client/test.py
This will allow us to send AC Loss and Low Battery to Home Assistant.
=> Expose AC Loss and Low Battery states

total_connect_client/TotalConnectClient.py
fixes https://github.com/home-assistant/home-assistant/issues/22056
=> add new GSMV4G device type

setup.py, total_connect_client/TotalConnectClient.py
Adding another panel name to the `VALID_DEVICES` array. Eventually, I'd like to refactor `get_security_panel_device_id()` to make it more generic, but we'd need to get some feedback from other users as to what those devices look like and how we can pick them out (I think there is a device_class attribute that might be what we need)
=> add panel and bump version

ALARM_STATUS.md, setup.py, tests/test_total_connect_client.py, tests/test_total_connect_zone.py, total_connect_client/TotalConnectClient.py, total_connect_client/live_test_auto_bypass.py
Fixes https://github.com/craigjmidwinter/total-connect-client/issues/50 and https://github.com/craigjmidwinter/total-connect-client/issues/51.
=> Fix 50 and 51

tests/test_total_connect_client.py, tests/test_total_connect_location.py, tests/test_total_connect_zone.py, total_connect_client/TotalConnectClient.py, total_connect_client/test.py
This PR should deal with the new response codes listed in the two new issues.  It also adds some other improvements I had been working on to improve location handling for Home Assistant.
=> Deal with two new response codes and other improvements

RESULT_CODES.md, setup.py, tests/test_total_connect_client.py, tests/test_total_connect_location.py, tests/test_total_connect_zone.py, total_connect_client/TotalConnectClient.py, total_connect_client/__init__.py, total_connect_client/test.py
=> Authentication improvements

RESULT_CODES.md, setup.py, tests/const.py, tests/test_get_zone_details.py, tests/test_total_connect_client.py, tests/test_total_connect_location.py, total_connect_client/TotalConnectClient.py, total_connect_client/test.py
=> fixes https://github.com/craigjmidwinter/total-connect-client/issues/63

total_connect_client/TotalConnectClient.py
first due to -120 result code.
=> Fix location.set_status() KeyError without location.set_zone_details()

RESULT_CODES.md, setup.py, tests/test_client_arm_disarm.py, total_connect_client/TotalConnectClient.py
Both functions now return True on success and False otherwise.
Both now use the main request() which better handles connection errors and other issues.
Added tests for both arm() and disarm().
Some minor code cleanup.
These updates are needed for https://github.com/home-assistant/core/issues/33301
=> Update arm() and disarm() 

DEPLOYMENT.md, setup.py
Hopefully fixes #83, although still not fully automated.
=> Add DEPLOYMENT.md notes for developers.  Bump version 0.55.2

tests/common.py, tests/const.py, tests/test_client_arm_disarm.py, tests/test_get_panel_meta_data.py, total_connect_client/TotalConnectClient.py, total_connect_client/live_test_arm.py, total_connect_client/live_test_disarm.py
=> Fix #90 by adjusting request() to handle session initiated.

README.md, RESULT_CODES.md, setup.py, tests/test_client_arm_disarm.py, total_connect_client/TotalConnectClient.py, total_connect_client/info.py, total_connect_client/live_test_arm.py, total_connect_client/live_test_auto_bypass.py, total_connect_client/live_test_disarm.py, total_connect_client/live_test_validate_usercode.py
=> Add validate_usercode(), related tests, and bump version to 0.55.6.

VERSIONS.md
Will aid in troubleshooting issues for users on older versions of HA.
=> Add TC-to-HA version mapping table

tests/const.py, tests/test_location.py, tests/test_user.py, tests/test_zone.py, total_connect_client/TotalConnectClient.py, tox.ini
Allow setting of auto-bypass mode per location.  This should allow for better control from HA in the future.  Improved tests.
Also a couple of other minor code improvements
=> Auto low battery bypass improvements

README.md
@austinmroczek is what I wrote correct? If not, let me know and I will change it.
=> document the actual interface we expect people to use

total_connect_client/TotalConnectClient.py, total_connect_client/location.py, total_connect_client/zone.py
See discussion in https://github.com/craigjmidwinter/total-connect-client/issues/125
=> expand is_type_button() and move arm_custom() to Location from Client

setup.py
New version corrects import error identified and fixed by @dulitz
=> bump to 2021.7.1

setup.py, tests/common.py, tests/const.py, tests/test_client_arm_disarm.py, tests/test_client_authenticate.py, tests/test_client_get_panel_meta_data.py, tests/test_client_init.py, tests/test_client_misc.py, tests/test_client_request.py, tests/test_client_validate_usercode.py, tests/test_client_zone_bypass.py, tests/test_device.py, tests/test_location.py, tests/test_location_arm_disarm.py, tests/test_partition.py, tests/test_zone.py, total_connect_client/__init__.py, total_connect_client/client.py, total_connect_client/const.py, total_connect_client/exceptions.py, total_connect_client/live/arm.py, total_connect_client/live/disarm.py, total_connect_client/location.py, total_connect_client/partition.py
=> bump version to 2021.08

setup.py, tests/test_partition.py, total_connect_client/partition.py
--adds test so we actually test that line of code...
--update code to fix it
=> Fix for #148

total_connect_client/client.py
now we also cache the WSDL and xsd files for an hour instead of refetching them for every. single. request.
=> set a 60 second timeout for network requests

setup.py
=> bump version to 2022.1

ALARM_STATUS.md, setup.py, tests/const.py, tests/test_partition.py, tests/test_zone.py, total_connect_client/const.py, total_connect_client/zone.py
Handles ProA7 ArmingStates 10219-10221 and 10230-10233.
Handles ZoneStatus 16
Bumps version to 2022.2
Fixes #176
Fixes #177
=> Handle various ProA7 panel codes

setup.py, total_connect_client/client.py, tox.ini
- fix #186 by raising ServiceUnavailable if we get token errors after max retries
- add py310 to testing
- bump version to 2022.5
=> fix incomplete authentication problem

total_connect_client/client.py
=> possibly fix Python 3.10 SSL error. passes unittests and works on Python 3.9

total_connect_client/location.py
Add a couple of type hints to fix #198
=> add type hints for some functions

README.md, pyproject.toml, tests/test_client_misc.py, tests/test_location.py, total_connect_client/location.py
- Improves handling of zones on startup and continues even if zero zones are returned. Fixes #205 (or at least helps with it)
- Minor doc fixes
=> Improve handling of no zones on startup

total_connect_client/const.py, total_connect_client/location.py, total_connect_client/sync.py
Add location.sync_panel() and location.get_sync_status() functions and script to run from command line.
=> add panel sync and status

tests/test_zone.py, total_connect_client/location.py, total_connect_client/zone.py
Adds a bypass function to TotalConnectZone.  This will simplify logic in use with HA.
Adds tests for the new function.
=> Add zone.bypass function

total_connect_client/bypass_all.py, total_connect_client/location.py
Adds a bypass_all and clear_bypass function for locations.  See #200 
Adds a temporary script for users to help us test live with their alarms.
=> Add bypass_all and clear_bypass functions

pyproject.toml, tests/const.py, tests/test_client_zone_bypass.py, tests/test_location_arm_disarm.py
Adds tests for zone_bypass_all() and clear_bypass()
=> add tests for bypass functions

pyproject.toml, total_connect_client/live/zwave.py
Updates the Z-wave test script
=> Update zwave test script

DEVICES.md, RESULT_CODES.md, total_connect_client/live/experimental.py
Improve the experimental script and device documentation
=> Update experimental script and docs

pyproject.toml, requirements_test.txt, tests/test_location.py, total_connect_client/const.py
- Properly handle ArmingState code 10215 which is a new code for carbon monoxide detected.
- Update requirements.txt for Zeep 4.2.1
- Update testing dependencies
=> Handle ArmingState code 10215

pyproject.toml, total_connect_client/cache/soap-encodings-schemas.xmlsoap.org.txt, total_connect_client/client.py
- First attempt to fix https://github.com/craigjmidwinter/total-connect-client/issues/223
- Distributes the SOAP file with the package
- Initiates Zeep with the local SOAP file
- Moves Python requirement to >=3.10
- Bump version to 2024.5
=> Add cached SOAP file

total_connect_client/client.py, total_connect_client/const.py
Handles ResultCode -123 (account locked) by raising an AuthenticationError.
=> handle ResultCode -123

total_connect_client/client.py, total_connect_client/const.py, total_connect_client/device.py, total_connect_client/location.py, total_connect_client/partition.py, total_connect_client/user.py, total_connect_client/zone.py
Various changes to improve typing in the package. This is about 80% of the way to Strict typing.
=> Improve typing 

pyproject.toml, tests/const.py, tests/test_location_arm_disarm.py, tests/test_partition.py, total_connect_client/location.py, total_connect_client/partition.py
- Improve typing for partition_id
- Update tests for partition_id
- Bump version to 2025.1
-
=> Improve typing for partition_id and bump version

pyproject.toml
Change version to 2025.1.2
Sorry I gave bad guidance in the previous comments
=> fix version to 2025.1.2

pyproject.toml, total_connect_client/client.py
Simplify mocking all of our requests in our HA tests.
Bumps version to 2025.1.4.
=> simplify mocking in HA tests

tests/test_client_authenticate.py, total_connect_client/client.py, total_connect_client/const.py
- Changes client.log_out to new API
- Updates associated tests
=> Switch client.log_out to new API

pyproject.toml, requirements.txt, requirements_test.txt, total_connect_client/client.py
- Adds a token_updater function to the OAuth2Session, so we don't get the TokenUpdated exception.  Fixes #265 
- Changes `client.token` to `client._logged_in` because we are really using this variable to determine if we are logged in, and due to other changes, no longer use it for anything else. OAuth2Session is handling the tokens now.  
- Removes `pyjwt` from TotalConnectClient and from pyproject.toml dependencies and requirements.txt.  We still use it for tests though, so added it to requirements_test.txt
Would greatly appreciate code review and suggestions/improvements.
=> Update client._request_token() 

tests/common.py, total_connect_client/client.py
Fix #263 by adjusting startup sequence to load full details by default, with retries.
=> Load details
