total_connect_client/TotalConnectClient.py
The Total Connect API lists my ```DeviceName``` as ```Security System``` instead of ```Security Panel```.  I'm not sure if they have updated this for all devices or it is just the newer ones (Honeywell Lyric Controller).  I added in the alternate ```DeviceName``` and am no longer getting the error mentioned in issue #4 @wardcraigj
=> Fixed 'No Security Panel Found' error

total_connect_client/TotalConnectClient.py
My lyric controller has the ability to arm only certain zones.  This is called "Armed Custom Bypass" and as a different alarm code.  This PR adds that alarm code so the status in home assistant isn't ```UNKNOWN```
=> adding ARMED_CUSTOM_BYPASS alarm code

total_connect_client/TotalConnectClient.py
I noticed that I was getting session expired errors.  This PR helps solve those issues.  It does 2 main things:
1.  Provide a ```keep_alive``` method that can be called to extend the session.
2.  Provide the ability to re-authenticate if a session has expired.
I also refactored some code that directly referenced various alarm codes to reference their respective constants.  This allows for more readability (in my opinion) and is easier to maintain in the long run.
=> Reconnect on session expiration

total_connect_client/TotalConnectClient.py
Arming and Disarming the system can result in either a `4500` result code or a `0` result code.  This PR takes the `4500` result code into account.
=> fixed logic issue around arm/disarm result code

total_connect_client/TotalConnectClient.py
I'm having the same problem as issue #14 (Panel named 'Lynx Touch-WiFi').  Added in additional case to account for this panel name.
=> Adding recognition of panel named Lynx Touch-WiFi

total_connect_client/TotalConnectClient.py, total_connect_client/test.py
Believe this fixes issue #16 by incorporating a usercode/PIN.  It defaults to '-1' if not passed, so the code should be backwards compatible.  
Also added another deviceName for 'ILP5' which system uses.
=> Fix issue #16 and another minor fix

total_connect_client/TotalConnectClient.py
Fixes #23 by removing `self` from the call to `VALID_DEVICES`
=> remove self from VALID_DEVICES call

total_connect_client/TotalConnectClient.py
Add 7874i support to total connect client. Currently the client supports a few devices. The 7874i is a wifi device used with various Vista-type panels.
=> Add 7874i support

total_connect_client/TotalConnectClient.py
With reference to: https://github.com/home-assistant/home-assistant/issues/22229
total-connect-client has a bug in the get_armed_status() function.
Can you please merge this PR and release to Pypi?
=> Fixed get_armed_status function

setup.py, tests/common.py, tests/const.py, tests/test_client_arm_disarm.py, tests/test_get_panel_meta_data.py, tests/test_get_zone_details.py, tests/test_total_connect_client.py, tests/test_total_connect_location.py, total_connect_client/TotalConnectClient.py, total_connect_client/info.py, total_connect_client/live_test_auto_bypass.py
Better handles result code -4502 Command Failed when trying to arm the system with a zone faulted. #81
Error checking for an empty PanelMetaDataAndStatus when updating status, and for None passed to Location.set_status(). #80  Added tests.
Various minor updates from running `black` and `isort` on the code.
=> Fix #80 and #81

tests/const.py, tests/test_client_arm_disarm.py, tests/test_client_get_panel_meta_data.py, tests/test_client_misc.py, tests/test_location.py, tests/test_location_arm_disarm.py, tests/test_partition.py, total_connect_client/__init__.py, total_connect_client/client.py, total_connect_client/const.py, total_connect_client/location.py, total_connect_client/partition.py
convert loose constants to enums ArmType and ArmingState. ArmingState incorporates predicates is_arming() etc. Specific arm methods have been moved to client.ArmingHelper.
tox passes.
This is a competitor to Armable. I like this better. This clarifies what an ArmingState is, and it organizes the large number of predicates to make it clear they are predicates on ArmingState. There's no abstract base class, just returning an enum.
This includes ArmingHelper as we discussed. Now that ArmType is an enum, I'm not sure there's a big difference between
```
ArmingHelper(partition_or_location).arm_stay_night()
```
and
```
partition_or_location.arm(ArmType.STAY_NIGHT)
```
but I'm happy to have ArmingHelper if it means not duplicating those methods.
I have a different PR for the ZoneType enum which …
=> factor arming state predicates into new enum ArmingState

ALARM_STATUS.md, setup.py, total_connect_client/const.py
Handle ArmingState of 10214 returned for the location.  Bump version to 2021.08.1
Fixes #144
=> Handle ArmingState 10214

total_connect_client/location.py, total_connect_client/partition.py, total_connect_client/zone.py
if we get an unknown ArmingState or ZoneStatus from the server, we log a message and raise the exception because we don't know how to proceed.
If we get an unknown ZoneType from the server, we log a message and continue because that won't affect our ability to function.
This also fixes a bug whereby ZoneType was not set to the num but was stored as the integer.
=> log unknown server responses

tests/test_client_request.py, total_connect_client/client.py
Some maybe can't be fixed by a retry but it won't hurt to retry here.
Unittests in python 3.7 has a bug when patching builtins.eval, so now we have a method _eval() that just calls eval(), only so that unittest dependency injection works.
tox passes py37.
=> retry all the exceptions that might be raised by SOAP's underlying HTTP transport

setup.py, total_connect_client/__init__.py
Makes the ResultCode enum public for use in Home Assistant testing.
Bump version to 2021.11.2
=> Make ResultCode public

tests/test_zone.py, total_connect_client/zone.py
Fixes #171 
Previously an unknown ZoneStatus was silently ignored.  Now it will generate a warning message in the log.
Added a test, and ran `black`
=> Handle unknown ZoneStatus

VERSIONS.md, setup.py, total_connect_client/client.py
The ResultCode -100 or AUTHENTICATION_FAILED seems to be an intermittent error, and not an indication of a bad username/password.  This PR retries the server request instead of triggering an AuthenticationError.
- Fixes #180 
- Bumps version to 2022.2.1
- Minor documentation update
=> Retry on AUTHENTICATION_FAILED 

README.md, setup.py, tests/test_client_arm_disarm.py, tests/test_client_request.py, total_connect_client/client.py, total_connect_client/exceptions.py, tox.ini
Previously when a user provided an invalid usercode, the BadResultCodeError exception was thrown, but we couldn't differentiate that from other problems.  Adds a new UsercodeInvalid exception to help with handling https://github.com/home-assistant/core/issues/68023.  
Update tests to match.
=> Update invalid usercode handling

setup.py, tests/const.py, tests/test_client_request.py, total_connect_client/client.py
Ensures we use the new token in request arguments immediately after re-authenticating.
Fixes #189
=> Update request args after re-authentication

.github/workflows/python-publish.yml
Uses GitHub Actions to push a new package to PyPI automatically when a release is tagged in GitHub
See https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-python#publishing-to-pypi
=> Publish to PyPI on new GitHub Release

pyproject.toml
- Update Zeep to 4.3.1 **https://github.com/mvantellingen/python-zeep/releases/tag/4.3.1**
- Bump version to 2024.12
=> latest zeep and bump version

total_connect_client/client.py, total_connect_client/location.py, total_connect_client/partition.py
Adds an optional `usercode` parameter in Location, Partition and ArmingHelper arm and disarm functions.
If usercode is not passed, it uses the already stored usercode from initial setup (which we currently use).  So this is backwards compatible.
Fixes #236
=> add optional usercode in arm and disarm functions

total_connect_client/client.py
Related to #245 , seems like the "ValidateUserCode" SOAP request has been deprecated and removed. Use the alternative "ValidateUserCodeEx" request instead, which still seems to be operational.
=> Use alternative ValidateUserCodeEx request for user code validation

requirements.txt, tests/common.py, tests/conftest.py, tests/const.py, tests/test_client_authenticate.py, tests/test_client_init.py, tests/test_client_request.py, tests/test_zone.py, total_connect_client/client.py, total_connect_client/const.py, total_connect_client/device.py, total_connect_client/location.py
Ref: #245 
Add functions to call the HTTP Web API, and switch over the SessionDetails request performed during login from SOAP to HTTP. To make a Web API request, use the `TotalConnectClient.http_request` function, only one call was switched here but this should make it straightforward to switch others in the future.
Other changes:
- I switched the ad-hoc OAuth2 implementation added in #243 to use `requests-oauthlib` instead. This library will refresh the session automatically if making HTTP requests. For now we still need some manual refresh code to handle the SOAP cases, but this can be removed eventually (along with the entire `request` function)
- The tests are somewhat simplified. Many of them were counting exact calls to SOAP, but now that requests are switching from HTTP -> SOAP …
=> Start using Web API

.devcontainer/devcontainer.json, total_connect_client/live/trigger.py, total_connect_client/location.py
The new API has a call for RemotePanicAlarm.  Added an experimental call to see if this could trigger the alarm panel via code.
Collecting results in https://github.com/craigjmidwinter/total-connect-client/issues/259
=> Add experimental trigger panel function
